Section "InputClass"
     Identifier "libinput touchpad catchall"
     MatchIsTouchpad "on"
     MatchDevicePath "/dev/input/event*"
     Option "Tapping" "True" # Touchpad tapping enabled
     Option "TappingDrag" "False" # Never drag
     Option "TransformationMatrix" "0.96 0 0 0 0.96 0 0 0 1" # Slight accel
     Driver "libinput"
EndSection

